### ISSUE TITLE
[commonjs--resolver] Unexpected character '' (Note that you need plugins to import files that are not JavaScript)

### ISSUE THREAD

**Issue by Namaskar-1F64F** [etherCorps/sveltekit-og#7]
The thing fails to build. 

**To Reproduce**

1. try using the package
2. fails to build

**Expected behavior**
It doesn't fail to build

- OS: Vercel

**Additional context**

```bash
[commonjs--resolver] Unexpected character '' (Note that you need plugins to import files that are not JavaScript)
--
21:14:25.612 | file: /vercel/path0/node_modules/.pnpm/@resvg+resvg-js@2.4.1/node_modules/@resvg/resvg-js/index.js:1:0
21:14:25.612 | 1: ELF>@�8@8	@x�x�...
21:14:25.612 | ^
21:14:25.612 | 2: �D��...
21:14:25.612 | 3: ,��51�,Ⱦ5�;/ؾ5_�,�5�;/��5z�...
21:14:25.614 | error during build:
21:14:25.614 | RollupError: Unexpected character '' (Note that you need plugins to import files that are not JavaScript)
21:14:25.614 | at error (file:///vercel/path0/node_modules/.pnpm/rollup@3.18.0/node_modules/rollup/dist/es/shared/node-entry.js:2105:30)
21:14:25.614 | at Module.error (file:///vercel/path0/node_modules/.pnpm/rollup@3.18.0/node_modules/rollup/dist/es/shared/node-entry.js:13174:16)
21:14:25.614 | at Module.tryParse (file:///vercel/path0/node_modules/.pnpm/rollup@3.18.0/node_modules/rollup/dist/es/shared/node-entry.js:13851:25)
21:14:25.614 | at Module.setSource (file:///vercel/path0/node_modules/.pnpm/rollup@3.18.0/node_modules/rollup/dist/es/shared/node-entry.js:13461:39)
21:14:25.615 | at ModuleLoader.addModuleSource (file:///vercel/path0/node_modules/.pnpm/rollup@3.18.0/node_modules/rollup/dist/es/shared/node-entry.js:23422:20)
21:14:25.641 | ELIFECYCLE  Command failed with exit code 1.
21:14:25.658 | Error: Command "pnpm build" exited with 1
```

I fixed this by including both:
```
	"@resvg/resvg-js": "^2.4.1",
	"satori": "^0.4.1"
```

It might just be resvg is needed, but when I didn't have satori  there was a different error: `ReferenceError: _a is not defined`. Which I did see some _a in types somewhere so maybe there's something funky going on there. 🤷

**Comment by theetherGit** [comment]
I'm also facing the same issue i found a different way which then give error with satori's yoga wasm package.
Let me see what i can do, or if you are able to fix it please suggest it to me. I'll update it.

**Comment by theetherGit** [comment]
@Namaskar-1F64F with your suggestion it worked on vercel, so now we have peer dependency on both.
for `ReferenceError: _a is not defined`: https://github.com/vercel/satori/issues/185#issue-1406414923 please go through this as satori is peer dependency u might get this issue.
