### ISSUE TITLE
Build it with adapter `@sveltejs/adapter-node`

### ISSUE THREAD

**Issue by thomastraum** [etherCorps/sveltekit-og#9]
Any advice on how to build with the node adapter?  

```
> Using @sveltejs/adapter-node
error during build:
RollupError: Unexpected character '�' (Note that you need plugins to import files that are not JavaScript)
    at error (file:///Users/thomastraum/Documents/code/js/search.anything.io/search.anything.io/node_modules/rollup/dist/es/shared/rollup.js:1967:30)
    at Module.error (file:///Users/thomastraum/Documents/code/js/search.anything.io/search.anything.io/node_modules/rollup/dist/es/shared/rollup.js:12962:16)
    at Module.tryParse (file:///Users/thomastraum/Documents/code/js/search.anything.io/search.anything.io/node_modules/rollup/dist/es/shared/rollup.js:13356:25)
    at Module.setSource (file:///Users/thomastraum/Documents/code/js/search.anything.io/search.anything.io/node_modules/rollup/dist/es/shared/rollup.js:13247:39)
    at ModuleLoader.addModuleSource (file:///Users/thomastraum/Documents/code/js/search.anything.io/search.anything.io/node_modules/rollup/dist/es/shared/rollup.js:22888:20)
```

I added `css()` to myplugins 

```

import { sveltekit } from '@sveltejs/kit/vite';
import css from "rollup-plugin-import-css";

/** @type {import('vite').UserConfig} */
const config = {
	plugins: [sveltekit(), css()]
};

export default config;

```

**Comment by theetherGit** [comment]
I'm going to need some time. I'm not outside without my laptop.

**Comment by thomastraum** [comment]
I think it might be related to the font files. They need a build plugin in Vite? My Vite skills aren’t that great. On 31 Mar 2023, at 21:16, Shivam Meena ***@***.***> wrote:﻿
I'm going to need some time. I'm not outside without my laptop.

**Comment by theetherGit** [comment]
ok. If you get stuck again let me know.

**Comment by thomastraum** [comment]
Sorry, it was a hunch that its related to the font files the plugin needs. I haven't solved it yet. I don't expect you to solve it, but I wanted to mention that, right now, the plugin doesn't build with a node adapter.

Thomas

**Comment by theetherGit** [comment]
Can you please guide me to reproduce this issue?

**Comment by thomastraum** [comment]
here is a repo with an example app and a node adaptor: https://github.com/thomastraum/sveltekit-og_node_build

**Comment by baseplate-admin** [comment]
Hi i can reproduce it. Here are the commands i used on [this](https://github.com/thomastraum/sveltekit-og_node_build) repo

```bash
baseplate-admin@pop-os:~/Programming/sveltekit-og_node_build$ npm i

up to date, audited 144 packages in 848ms

17 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
baseplate-admin@pop-os:~/Programming/sveltekit-og_node_build$ npm run build

> sveltekit-og-node-build@0.0.1 build
> vite build


vite v4.2.1 building SSR bundle for production...
transforming (80) src/routes/styles.css"confetti" is imported from external module "@neoconfetti/svelte" but never used in "src/routes/sverdle/+page.svelte".
✓ 80 modules transformed.
11:40:18 AM [vite-plugin-svelte] ssr compile done.
package                	files	 time	   avg
sveltekit-og-node-build	    9	0.17s	19.2ms

vite v4.2.1 building for production...
✓ 68 modules transformed.
11:40:21 AM [vite-plugin-svelte] dom compile done.
package                	files	 time	   avg
sveltekit-og-node-build	    9	0.36s	40.1ms
.svelte-kit/output/client/_app/version.json                                                         0.03 kB
.svelte-kit/output/client/_app/immutable/assets/github.1ea8d62e.svg                                 1.75 kB
.svelte-kit/output/client/_app/immutable/assets/svelte-logo.87df40b8.svg                            1.89 kB
.svelte-kit/output/client/_app/immutable/assets/fira-mono-greek-ext-400-normal.9e2fe623.woff2       7.51 kB
.svelte-kit/output/client/_app/immutable/assets/fira-mono-cyrillic-400-normal.c7d433fd.woff2        9.10 kB
.svelte-kit/output/client/vite-manifest.json                                                       10.09 kB
.svelte-kit/output/client/_app/immutable/assets/fira-mono-greek-400-normal.a8be01ce.woff2          10.52 kB
.svelte-kit/output/client/_app/immutable/assets/fira-mono-latin-ext-400-normal.6bfabd30.woff2      11.36 kB
.svelte-kit/output/client/_app/immutable/assets/fira-mono-cyrillic-ext-400-normal.3df7909e.woff2   15.77 kB
.svelte-kit/output/client/_app/immutable/assets/fira-mono-latin-400-normal.e43b3538.woff2          16.28 kB
.svelte-kit/output/client/_app/immutable/assets/fira-mono-all-400-normal.1e3b098c.woff             77.36 kB
.svelte-kit/output/client/_app/immutable/assets/svelte-welcome.c18bcf5a.webp                      115.47 kB
.svelte-kit/output/client/_app/immutable/assets/svelte-welcome.6c300099.png                       360.81 kB
.svelte-kit/output/client/_app/immutable/assets/_page.89a9e780.css                                  0.81 kB │ gzip: 0.35 kB
.svelte-kit/output/client/_app/immutable/assets/_page.265a38f0.css                                  1.45 kB │ gzip: 0.53 kB
.svelte-kit/output/client/_app/immutable/assets/_page.9d501049.css                                  3.80 kB │ gzip: 1.07 kB
.svelte-kit/output/client/_app/immutable/assets/_layout.fa9427ff.css                                5.18 kB │ gzip: 1.66 kB
.svelte-kit/output/client/_app/immutable/chunks/environment.9aa685ef.js                             0.03 kB │ gzip: 0.05 kB
.svelte-kit/output/client/_app/immutable/entry/_page.js.9c5eea7e.js                                 0.07 kB │ gzip: 0.08 kB
.svelte-kit/output/client/_app/immutable/chunks/1.4a1a82e6.js                                       0.08 kB │ gzip: 0.10 kB
.svelte-kit/output/client/_app/immutable/chunks/0.dcc0be50.js                                       0.09 kB │ gzip: 0.10 kB
.svelte-kit/output/client/_app/immutable/chunks/4.43ea9cb6.js                                       0.09 kB │ gzip: 0.10 kB
.svelte-kit/output/client/_app/immutable/entry/about-page.js.13bb5e39.js                            0.13 kB │ gzip: 0.12 kB
.svelte-kit/output/client/_app/immutable/entry/sverdle-how-to-play-page.js.13bb5e39.js              0.13 kB │ gzip: 0.13 kB
.svelte-kit/output/client/_app/immutable/chunks/2.fd4b5db5.js                                       0.14 kB │ gzip: 0.13 kB
.svelte-kit/output/client/_app/immutable/chunks/_page.da46b06b.js                                   0.14 kB │ gzip: 0.14 kB
.svelte-kit/output/client/_app/immutable/chunks/3.87b68960.js                                       0.14 kB │ gzip: 0.13 kB
.svelte-kit/output/client/_app/immutable/chunks/5.7851047f.js                                       0.16 kB │ gzip: 0.14 kB
.svelte-kit/output/client/_app/immutable/chunks/_page.1806d283.js                                   0.20 kB │ gzip: 0.18 kB
.svelte-kit/output/client/_app/immutable/chunks/_page.40474c2a.js                                   0.20 kB │ gzip: 0.18 kB
.svelte-kit/output/client/_app/immutable/chunks/stores.81112e4c.js                                  0.24 kB │ gzip: 0.17 kB
.svelte-kit/output/client/_app/immutable/chunks/index.5d96a4e7.js                                   0.50 kB │ gzip: 0.33 kB
.svelte-kit/output/client/_app/immutable/entry/error.svelte.7da002a4.js                             0.80 kB │ gzip: 0.50 kB
.svelte-kit/output/client/_app/immutable/chunks/parse.d12b0d5b.js                                   1.32 kB │ gzip: 0.65 kB
.svelte-kit/output/client/_app/immutable/chunks/singletons.5c2711d0.js                              2.43 kB │ gzip: 1.25 kB
.svelte-kit/output/client/_app/immutable/entry/about-page.svelte.1e89b34e.js                        2.48 kB │ gzip: 1.12 kB
.svelte-kit/output/client/_app/immutable/entry/_layout.svelte.eee0a389.js                           5.14 kB │ gzip: 1.95 kB
.svelte-kit/output/client/_app/immutable/entry/sverdle-how-to-play-page.svelte.993f3007.js          5.25 kB │ gzip: 1.97 kB
.svelte-kit/output/client/_app/immutable/entry/_page.svelte.b2c28aa7.js                             5.67 kB │ gzip: 2.52 kB
.svelte-kit/output/client/_app/immutable/entry/app.609fc937.js                                      6.69 kB │ gzip: 2.49 kB
.svelte-kit/output/client/_app/immutable/chunks/index.bead85c3.js                                   8.35 kB │ gzip: 3.41 kB
.svelte-kit/output/client/_app/immutable/entry/sverdle-page.svelte.1f2c4c03.js                     16.08 kB │ gzip: 6.61 kB
.svelte-kit/output/client/_app/immutable/entry/start.015a4ee2.js                                   22.09 kB │ gzip: 8.81 kB
✓ built in 1.10s
.svelte-kit/output/server/_app/immutable/assets/github.1ea8d62e.svg                                 1.75 kB
.svelte-kit/output/server/_app/immutable/assets/svelte-logo.87df40b8.svg                            1.89 kB
.svelte-kit/output/server/vite-manifest.json                                                        7.36 kB
.svelte-kit/output/server/_app/immutable/assets/fira-mono-greek-ext-400-normal.9e2fe623.woff2       7.51 kB
.svelte-kit/output/server/_app/immutable/assets/fira-mono-cyrillic-400-normal.c7d433fd.woff2        9.10 kB
.svelte-kit/output/server/_app/immutable/assets/fira-mono-greek-400-normal.a8be01ce.woff2          10.52 kB
.svelte-kit/output/server/_app/immutable/assets/fira-mono-latin-ext-400-normal.6bfabd30.woff2      11.36 kB
.svelte-kit/output/server/_app/immutable/assets/fira-mono-cyrillic-ext-400-normal.3df7909e.woff2   15.77 kB
.svelte-kit/output/server/_app/immutable/assets/fira-mono-latin-400-normal.e43b3538.woff2          16.28 kB
.svelte-kit/output/server/_app/immutable/assets/fira-mono-all-400-normal.1e3b098c.woff             77.36 kB
.svelte-kit/output/server/_app/immutable/assets/svelte-welcome.c18bcf5a.webp                      115.47 kB
.svelte-kit/output/server/_app/immutable/assets/svelte-welcome.6c300099.png                       360.81 kB
.svelte-kit/output/server/_app/immutable/assets/_page.0e6c8ae6.css                                  0.84 kB
.svelte-kit/output/server/_app/immutable/assets/_page.08e4d5ca.css                                  1.45 kB
.svelte-kit/output/server/_app/immutable/assets/_page.b0e588ca.css                                  3.87 kB
.svelte-kit/output/server/_app/immutable/assets/_layout.c2b8d7ae.css                                6.14 kB
.svelte-kit/output/server/chunks/prod-ssr.js                                                        0.04 kB
.svelte-kit/output/server/entries/pages/_page.js                                                    0.05 kB
.svelte-kit/output/server/chunks/environment.js                                                     0.08 kB
.svelte-kit/output/server/entries/pages/about/_page.js                                              0.13 kB
.svelte-kit/output/server/entries/pages/sverdle/how-to-play/_page.js                                0.13 kB
.svelte-kit/output/server/internal.js                                                               0.19 kB
.svelte-kit/output/server/chunks/stores.js                                                          0.47 kB
.svelte-kit/output/server/entries/fallbacks/error.svelte.js                                         0.47 kB
.svelte-kit/output/server/entries/pages/about/_page.svelte.js                                       1.06 kB
.svelte-kit/output/server/chunks/index2.js                                                          1.33 kB
.svelte-kit/output/server/chunks/index.js                                                           2.04 kB
.svelte-kit/output/server/entries/pages/sverdle/how-to-play/_page.svelte.js                         2.82 kB
.svelte-kit/output/server/entries/pages/_layout.svelte.js                                           4.43 kB
.svelte-kit/output/server/chunks/index3.js                                                          4.43 kB
.svelte-kit/output/server/chunks/internal.js                                                        5.33 kB
.svelte-kit/output/server/entries/pages/_page.svelte.js                                             7.31 kB
.svelte-kit/output/server/entries/pages/sverdle/_page.svelte.js                                     8.52 kB
.svelte-kit/output/server/index.js                                                                 82.12 kB
.svelte-kit/output/server/entries/pages/sverdle/_page.server.js                                   146.19 kB
.svelte-kit/output/server/entries/endpoints/og/_server.js                                         902.42 kB

Run npm run preview to preview your production build locally.

> Using @sveltejs/adapter-node
error during build:
RollupError: Unexpected character '' (Note that you need plugins to import files that are not JavaScript)
    at error (file:///home/baseplate-admin/Programming/sveltekit-og_node_build/node_modules/rollup/dist/es/shared/node-entry.js:2128:30)
    at Module.error (file:///home/baseplate-admin/Programming/sveltekit-og_node_build/node_modules/rollup/dist/es/shared/node-entry.js:13322:16)
    at Module.tryParse (file:///home/baseplate-admin/Programming/sveltekit-og_node_build/node_modules/rollup/dist/es/shared/node-entry.js:13999:25)
    at Module.setSource (file:///home/baseplate-admin/Programming/sveltekit-og_node_build/node_modules/rollup/dist/es/shared/node-entry.js:13609:39)
    at ModuleLoader.addModuleSource (file:///home/baseplate-admin/Programming/sveltekit-og_node_build/node_modules/rollup/dist/es/shared/node-entry.js:23574:20)
 ```

**Comment by theetherGit** [comment]
So sorry last month was little bit hectic because of my office work. Now, I'll get back to it and try to patch this issue.

**Comment by baseplate-admin** [comment]
Sure take your time

**Comment by theetherGit** [comment]
@baseplate-admin @thomastraum it's fixed now,

```js
"dependencies": {
		"@resvg/resvg-js": "^2.4.1",
		"satori": "^0.10.1"
	}
```

Add this in package json file after updating to newer version

**Comment by jasongitmail** [comment]
Possibility related:

I have `sveltekit-og` working when running using `npm run dev`. 
But with `npm run build && npm run preview`, I encounter the errors below. I'm using Cloudflare adapter:

```sh
error during build:
Error: Build failed with 4 errors:
.svelte-kit/output/server/entries/endpoints/og/_server.js:27355:43: ERROR: Could not resolve "url"
node_modules/@resvg/resvg-js/js-binding.js:1:52: ERROR: Could not resolve "fs"
node_modules / @resvg / resvg - js / js - binding.js: 1: 73: ERROR: Could not resolve "path"


Run npm run preview to preview your production build locally.  
  
> Using @sveltejs/adapter-cloudflare
✘ [ERROR] Could not resolve "url"

    .svelte-kit/output/server/entries/endpoints/og/_server.js:27355:43:
      27355 │ typeof URL !== "undefined" ? URL : require("url").URL;
            ╵                                            ~~~~~

  The package "url" wasn't found on the file system but is built into node. Are you trying to bundle
  for node? You can use "platform: 'node'" to do that, which will remove this error.
```


I interpret this to suggest that `resvg-js` may require NodeJS `fs` module, which isn't available on Cloudflare.

**Comment by theetherGit** [comment]
@thomastraum in this scenario i can only see wasm implementation more better

**Comment by jasongitmail** [comment]
@theetherGit That'd make sense to me. Something like [svg2png-wasm](https://github.com/ssssota/svg2png-wasm)

**Comment by theetherGit** [comment]
@jasongitmail please check og-resvg-branch but it's not working on cloudflare because of polyfill issue. I'll try it with [svg2png-wasm](https://github.com/ssssota/svg2png-wasm). if it works then i'm ok with it.

**Comment by theetherGit** [comment]
@jasongitmail as of now i have tested it on vercel, node and netlify. Working on all and added example for all in example directory currently it's going to live in og-resvg-wasm branch. Now i'll look into what we can do for cloudflare.

**Comment by jasongitmail** [comment]
Update: 
- `npm run build` still shows [the same 4 errors ](https://github.com/etherCorps/sveltekit-og/issues/9#issuecomment-1580904989)that I posted above. 
- But despite the build errors, `npm run preview` shows OG image generation working _successfully_.
- When I rename `og/+server.js` to `og/z+server.js` to prevent the file being included in the build, `npm run build` _passes without any errors_. 

I deleted `.svelte-kit` before running these tests to ensure nothing in the build cache affected the results.

To reproduce the error:
1. `npm i -D @sveltejs/adapter-cloudflare`
2. Use `import adapter from '@sveltejs/adapter-cloudflare';` in `svelte.config.js`
3. `npm run build`. It should show [the same 4 errors ] I linked above.

I'm using `og-resvg-wasm` branch, commit `3306bf0`.

**Comment by theetherGit** [comment]
@jasongitmail please use commit `82ff2df`. I pushed two things.

**Comment by theetherGit** [comment]
I have now examples for all `js runtime` so u can use them.
<img width="1597" alt="Screenshot 2023-06-07 at 10 17 56 PM" src="https://github.com/etherCorps/sveltekit-og/assets/71087863/42c2b660-032e-4fd2-9d85-702ca7300634">

**Comment by jasongitmail** [comment]
Similar result with the example:

I ran:
```
cd sveltekit-og/examples/cf-page-build
pnpm install
pnpm build
// Visit http://localhost:4173/
```
The image is generated, but the same 4 build errors exist.

What's your NodeJS version? I'm using `v20.1.0` Node is used for the build process, so it could be related to that. 

```
> Using @sveltejs/adapter-cloudflare
✘ [ERROR] Could not resolve "fs"

    .svelte-kit/output/server/chunks/index2.js:3:7:
      3 │ import "fs";
        ╵        ~~~~

  The package "fs" wasn't found on the file system but is built into node. Are you trying to
  bundle for node? You can use "platform: 'node'" to do that, which will remove this error.

✘ [ERROR] Could not resolve "path"

    .svelte-kit/output/server/chunks/index2.js:4:24:
      4 │ import { dirname } from "path";
        ╵                         ~~~~~~

  The package "path" wasn't found on the file system but is built into node. Are you trying to
  bundle for node? You can use "platform: 'node'" to do that, which will remove this error.

✘ [ERROR] Could not resolve "url"

    .svelte-kit/output/server/chunks/index2.js:5:30:
      5 │ import { fileURLToPath } from "url";
        ╵                               ~~~~~

  The package "url" wasn't found on the file system but is built into node. Are you trying to
  bundle for node? You can use "platform: 'node'" to do that, which will remove this error.

✘ [ERROR] Could not resolve "url"

    .svelte-kit/output/server/chunks/index2.js:25910:43:
      25910 │ typeof URL !== "undefined" ? URL : require("url").URL;
            ╵                                            ~~~~~

  The package "url" wasn't found on the file system but is built into node. Are you trying to
  bundle for node? You can use "platform: 'node'" to do that, which will remove this error.

error during build:
Error: Build failed with 4 errors:
.svelte-kit/output/server/chunks/index2.js:3:7: ERROR: Could not resolve "fs"
.svelte-kit/output/server/chunks/index2.js:4:24: ERROR: Could not resolve "path"
.svelte-kit/output/server/chunks/index2.js:5:30: ERROR: Could not resolve "url"
.svelte-kit/output/server/chunks/index2.js:25910:43: ERROR: Could not resolve "url"
    at failureErrorWithLog (/Users/code/temp/sveltekit-og/examples/cf-page-build/node_modules/.pnpm/esbuild@0.17.19/node_modules/esbuild/lib/main.js:1636:15)
    at /Users/code/temp/sveltekit-og/examples/cf-page-build/node_modules/.pnpm/esbuild@0.17.19/node_modules/esbuild/lib/main.js:1048:25
    at /Users/code/temp/sveltekit-og/examples/cf-page-build/node_modules/.pnpm/esbuild@0.17.19/node_modules/esbuild/lib/main.js:993:52
    at buildResponseToResult (/Users/code/temp/sveltekit-og/examples/cf-page-build/node_modules/.pnpm/esbuild@0.17.19/node_modules/esbuild/lib/main.js:1046:7)
    at /Users/code/temp/sveltekit-og/examples/cf-page-build/node_modules/.pnpm/esbuild@0.17.19/node_modules/esbuild/lib/main.js:1075:16
    at responseCallbacks.<computed> (/Users/code/temp/sveltekit-og/examples/cf-page-build/node_modules/.pnpm/esbuild@0.17.19/node_modules/esbuild/lib/main.js:697:9)
    at handleIncomingPacket (/Users/code/temp/sveltekit-og/examples/cf-page-build/node_modules/.pnpm/esbuild@0.17.19/node_modules/esbuild/lib/main.js:752:9)
    at Socket.readFromStdout (/Users/code/temp/sveltekit-og/examples/cf-page-build/node_modules/.pnpm/esbuild@0.17.19/node_modules/esbuild/lib/main.js:673:7)
    at Socket.emit (node:events:511:28)
    at addChunk (node:internal/streams/readable:332:12)
 ELIFECYCLE  Command failed with exit code 1.
```

Could it be one of Satori's dependencies?
```sh
# npm list --omit=dev --all
├── @resvg/resvg-wasm@2.4.1
└─┬ satori@0.10.1
  ├─┬ @shuding/opentype.js@1.4.0-beta.0
  │ ├── fflate@0.7.4
  │ └── string.prototype.codepointat@0.2.1
  ├── css-background-parser@0.1.0
  ├── css-box-shadow@1.0.0-3
  ├─┬ css-to-react-native@3.2.0
  │ ├── camelize@1.0.1
  │ ├── css-color-keywords@1.0.0
  │ └── postcss-value-parser@4.2.0 deduped
  ├── emoji-regex@10.2.1
  ├── escape-html@1.0.3
  ├─┬ linebreak@1.1.0
  │ ├── base64-js@0.0.8
  │ └─┬ unicode-trie@2.0.0
  │   ├── pako@0.2.9
  │   └── tiny-inflate@1.0.3
  ├─┬ parse-css-color@0.2.1
  │ ├── color-name@1.1.4
  │ └── hex-rgb@4.3.0
  ├── postcss-value-parser@4.2.0
  └── yoga-wasm-web@0.3.3
```

**Comment by theetherGit** [comment]
I'm using node v18 lts.

**Comment by jasongitmail** [comment]
I clicked the link in my error messages at `.svelte-kit/output/server/chunks/index2.js:3:7:`

This is the top of the contents of that file:
```
//.svelte-kit/output/server/chunks/index2.js

import satori from "satori";
import { Resvg, initWasm } from "@resvg/resvg-wasm";
import "fs";
import { dirname } from "path";
import { fileURLToPath } from "url";
typeof process !== "undefined" && process.hrtime ? () => {
  const t = process.hrtime();
  return t[0] * 1e3 + t[1] / 1e6;
} : () => self.performance.now();
var astralIdentifierCodes = [509, 0, 227, 0, 150, 4, 294, 9, 1368, 2, 2, 1, 6, 3, 41, 2, 5, 0, 166, 1, 574, 3, 9, 9, 370, 1, 81, 2, 71, 10, 50, 3, 123, 2, 54, 14, 32, 10, 3, 1, 11, 3, 46, 10, 8, 0, 46, 9, 7, 2, 37, 13, 2, 9, 6, 1, 45, 0, 13, 2, 

...
```

**Comment by theetherGit** [comment]
I think we are not using same commit please latest one i have made the changes where we don't use 

```js
import "fs";
import { dirname } from "path";
import { fileURLToPath } from "url";

```

**Comment by jasongitmail** [comment]
I'm using `82ff2df - (HEAD -> og-resvg-wasm, origin/og-resvg-wasm) netlify test` from Github. You?

**Comment by theetherGit** [comment]
@jasongitmail I have tried and made it work with `adapter-cloudflare-workers`. But You have to make a copy of sveltekit adapter and provide `esbuild nodemodules polyfills`. 

This will do the job

**Comment by theetherGit** [comment]
I'll push it then you can test and i'll release it.

For `polyfills` I tried other things but i was not able to do it. For this we can put it for later,

[Sveltekit Node Compact SUpport](https://github.com/sveltejs/kit/issues/10028)

[Sveltekit issue for esbuild confiiguration](https://github.com/sveltejs/kit/issues/3733)

**Comment by theetherGit** [comment]
Everythings is in `main` branch. 

I just pushed the code for it and now you can use it by installing `url` package in ur `devDependency` or `dependency`.

@jasongitmail Please test it and let me know if it works. then i'll publish it with docs

**Comment by jasongitmail** [comment]
@theetherGit I tested using the `main` branch of `@ethercorps/sveltekit-og` commit `97d7c42`.

- Using `url` package in `@ethercorps/sveltekit-og` removed that error.
- Inside `examples/cf-page-build`'s node_module's `@sveltejs/adapter-cloudflare` I ran `npm I -D @esbuild-plugins/node-modules-polyfill`. Inside  `@sveltejs/adapter-cloudflare/index.js` I imported it via `import nodeModulesPolyfill from '@esbuild-plugins/node-modules-polyfill';` and enabled it:
```js
await esbuild.build({
	platform: 'browser',
	conditions: ['worker', 'browser'],
	sourcemap: 'linked',
	target: 'es2022',
	entryPoints: [`${tmp}/_worker.js`],
	outfile: `${dest}/_worker.js`,
	allowOverwrite: true,
	format: 'esm',
	bundle: true,
	loader: {
		'.wasm': 'copy'
	},
	plugins: [nodeModulesPolyfill.default()], // < added this line
});
```
(just to test it, I can fork it later)
- Then inside `sveltekit-og/examples/cf-page-build` I ran `npm run build`.

## Result

- The error related to `url` is gone by installing `url` package. The pollyfill removed the errors related to `fs` and `path`.
- One error remains that fails the build. 
```sh
✘ [ERROR] No loader is configured for ".node" files: node_modules/@resvg/resvg-js-darwin-arm64/resvgjs.darwin-arm64.node

    node_modules/@resvg/resvg-js/js-binding.js:1:2594:
      1 │ ...darwin-arm64.node"):nativeBinding=require("@resvg/resvg-js-darwin-arm64")}catch(e){loadError=e}break;default:th
```

it appears it might not be using WASM version of resvg for some reason.

**Comment by theetherGit** [comment]
but i'm not `@resvg/resvg-js`  or `@resvg/resvg-wasm` i'm using `svg2png-wasm` because it's same as `@resvg/resvg-wasm` but have some better features with `scale` and `backgroundColor`. The main reason i switched was it's standalone and easy to tweak if needed in future. 

And for Using it, You don't have to rely on complete polyfills that's why i went for `url` package. In future cloudflare will add support for it in `workerd` runtime.

## Guide to use with Cloudflare Workers

1. pnpm i -D @ethercorps/sveltekit-og url
2. Use as provided in Quick guide.

That's all you have to do now.

**Comment by theetherGit** [comment]
@jasongitmail ✘ [ERROR] No loader is configured for ".node" files: node_modules/@resvg/resvg-js-darwin-arm64/resvgjs.darwin-arm64.node I have read something about this and it's support in vite and sveltekit but i was unable to do anything.

**Comment by theetherGit** [comment]
@jasongitmail  Can you do me a favor?  (I'm not that good with documentation yet)

If yes please update the readme as per new changes and runtime based.

**Comment by jasongitmail** [comment]
Yeah, I can try again with the NPM version tomorrow and update the docs.

**Comment by theetherGit** [comment]
Sure as of now this issue is fixed.

**Comment by jasongitmail** [comment]
@theetherGit v2.0.0 on NPM worked for me 🥳  (I.e. `npm run dev` generates the OG image and `npm run build` has no errors and `npm run preview` generates the og image. 

..._but_ it only worked after I edited `node_modules/etherCorps/sveltekit-og/index.js` from:
`import toReactElement from './toReactElement';`
to 
`import toReactElement from './toReactElement.js';`

Otherwise it gave an error of
```
Internal server error: Cannot find module
'/myapp/node_modules/@ethercorps/sveltekit-og/toReactElement'
imported from
/myapp/node_modules/@ethercorps/sveltekit-og/index.js
```

That was the only issue I encountered

**Comment by theetherGit** [comment]
ok, can you please push the change? 

I'm not getting this can you please tell me where it's getting this issue like adapter and node version.

**Comment by jasongitmail** [comment]
node v20.2.0
```json
"@ethercorps/sveltekit-og": "^2.0.0",
"@sveltejs/adapter-cloudflare": "^2.3.0",
"@sveltejs/kit": "^1.20.2",
```
It's probably not adapter related because it occurs during `npm run dev` too. 

I don't use TypeScript. But my understanding from a quick search is:

> One workaround is to include the .js extension in your TypeScript imports, even though the files are .ts.  TypeScript's module resolution understands that .js files are to be treated as .ts files in the context of a TypeScript project. Even though myModule.js is actually myModule.ts, TypeScript will correctly import it, and the resulting JavaScript output will have the correct .js extension in the import statement.


[PR](https://github.com/etherCorps/sveltekit-og/pull/18) untested

**Comment by theetherGit** [comment]
Understood if i'm not wrong it comes from ViteJs  because it supports multiple format and I read something related to this but i'm unable to recall it. 

Please continue anything related to this in discussions.
